package com.example.yuekao0316.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.yuekao0316.db.GoodsEntity;
import com.example.yuekao0316.db.GwcEntity;

import com.example.yuekao0316.db.GoodsEntityDao;
import com.example.yuekao0316.db.GwcEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsEntityDaoConfig;
    private final DaoConfig gwcEntityDaoConfig;

    private final GoodsEntityDao goodsEntityDao;
    private final GwcEntityDao gwcEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsEntityDaoConfig = daoConfigMap.get(GoodsEntityDao.class).clone();
        goodsEntityDaoConfig.initIdentityScope(type);

        gwcEntityDaoConfig = daoConfigMap.get(GwcEntityDao.class).clone();
        gwcEntityDaoConfig.initIdentityScope(type);

        goodsEntityDao = new GoodsEntityDao(goodsEntityDaoConfig, this);
        gwcEntityDao = new GwcEntityDao(gwcEntityDaoConfig, this);

        registerDao(GoodsEntity.class, goodsEntityDao);
        registerDao(GwcEntity.class, gwcEntityDao);
    }
    
    public void clear() {
        goodsEntityDaoConfig.clearIdentityScope();
        gwcEntityDaoConfig.clearIdentityScope();
    }

    public GoodsEntityDao getGoodsEntityDao() {
        return goodsEntityDao;
    }

    public GwcEntityDao getGwcEntityDao() {
        return gwcEntityDao;
    }

}
