package com.example.yuekao0316.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GWC_ENTITY".
*/
public class GwcEntityDao extends AbstractDao<GwcEntity, Long> {

    public static final String TABLENAME = "GWC_ENTITY";

    /**
     * Properties of entity GwcEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Pic = new Property(1, String.class, "pic", false, "PIC");
        public final static Property Titile = new Property(2, String.class, "titile", false, "TITILE");
        public final static Property Num = new Property(3, int.class, "num", false, "NUM");
        public final static Property IsChecked = new Property(4, Boolean.class, "isChecked", false, "IS_CHECKED");
    }


    public GwcEntityDao(DaoConfig config) {
        super(config);
    }
    
    public GwcEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GWC_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PIC\" TEXT NOT NULL ," + // 1: pic
                "\"TITILE\" TEXT NOT NULL ," + // 2: titile
                "\"NUM\" INTEGER NOT NULL ," + // 3: num
                "\"IS_CHECKED\" INTEGER);"); // 4: isChecked
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GWC_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GwcEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPic());
        stmt.bindString(3, entity.getTitile());
        stmt.bindLong(4, entity.getNum());
 
        Boolean isChecked = entity.getIsChecked();
        if (isChecked != null) {
            stmt.bindLong(5, isChecked ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GwcEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPic());
        stmt.bindString(3, entity.getTitile());
        stmt.bindLong(4, entity.getNum());
 
        Boolean isChecked = entity.getIsChecked();
        if (isChecked != null) {
            stmt.bindLong(5, isChecked ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GwcEntity readEntity(Cursor cursor, int offset) {
        GwcEntity entity = new GwcEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // pic
            cursor.getString(offset + 2), // titile
            cursor.getInt(offset + 3), // num
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0 // isChecked
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GwcEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPic(cursor.getString(offset + 1));
        entity.setTitile(cursor.getString(offset + 2));
        entity.setNum(cursor.getInt(offset + 3));
        entity.setIsChecked(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GwcEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GwcEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GwcEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
